// Master registry of every page/route in the app, used by the Project Board.
export const ALL_PAGES = [
  { path: '/', label: 'Command Hub' },
  { path: '/notices', label: 'Notices' },
  { path: '/calendar', label: 'Monthly Calendar' },
  { path: '/tasks', label: 'DC/2IC Task List' },
  { path: '/my-progress', label: 'My Progress' },
  { path: '/my-logbooks', label: 'My Logbook' },
  { path: '/forms-resources', label: 'Forms & Resources' },
  { path: '/my-availability', label: 'My Availability' },
  { path: '/my-qualifications', label: 'My Qualifications' },
  { path: '/my-governance', label: 'My Governance' },
  { path: '/personnel', label: 'Cadet Profiles' },
  { path: '/new-joiners', label: 'New Joiners' },
  { path: '/progress', label: 'Progress Matrix' },
  { path: '/promotion-readiness', label: 'Promotion Readiness' },
  { path: '/wht', label: 'Cadet WHTs' },
  { path: '/discipline-logs', label: 'Discipline / SG Log' },
  { path: '/uniform-exchange', label: 'Uniform Requests' },
  { path: '/course-request', label: 'Course Requests' },
  { path: '/report-issue', label: 'Issues Log' },
  { path: '/awards', label: 'Awards' },
  { path: '/cfav-roll', label: 'CFAV Nominal Roll' },
  { path: '/instructor-quals', label: 'CFAV Qualifications' },
  { path: '/all-availability', label: 'CFAV Availability' },
  { path: '/instructor-engagement', label: 'Engagement Log' },
  { path: '/parade', label: 'Parade Nominal Roll' },
  { path: '/attendance', label: 'Lesson Nominal Roll' },
  { path: '/schedule', label: 'Training Plan' },
  { path: '/training-manager', label: 'Training Manager' },
  { path: '/community-engagement', label: 'CE / KA Session Entry' },
  { path: '/bulk-progress', label: 'Bulk Progress Entry' },
  { path: '/syllabus', label: 'Syllabus' },
  { path: '/personal-syllabus', label: 'Ad-Hoc Syllabus' },
  { path: '/plan-generator', label: 'AI Plan Generator' },
  { path: '/training-plan-export', label: 'Export PDF' },
  { path: '/conflict-monitor', label: 'Conflict Monitor' },
  { path: '/analytics', label: 'Analytics' },
  { path: '/monthly-reports', label: 'Monthly Reports' },
  { path: '/duty-roster', label: 'Duty Roster' },
  { path: '/instructor-performance', label: 'Instructor Performance' },
  { path: '/naafi-management', label: 'NAAFI Management' },
  { path: '/admin', label: 'Global Settings' },
  { path: '/logic-dashboard', label: 'Logic Dashboard' },
  { path: '/audit-log', label: 'System Audit Log' },
  { path: '/help', label: 'Help & Wiki' },
  { path: '/ka-sessions', label: 'KA Sessions' },
  { path: '/keeping-active', label: 'Keeping Active Tracker' },
  { path: '/ka-session-new', label: 'New KA Session' },
  { path: '/ka-leaderboard', label: 'KA Leaderboard' },
  { path: '/form-creator', label: 'Form Creator' },
  { path: '/healthy-minds', label: 'Healthy Minds' },
  { path: '/staff-availability', label: 'Staff Availability' },
];